<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Генерация-случайных-величин" data-toc-modified-id="Генерация-случайных-величин-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Генерация случайных величин</a></span><ul class="toc-item"><li><span><a href="#Seed" data-toc-modified-id="Seed-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Seed</a></span></li><li><span><a href="#Равномерное-распределение" data-toc-modified-id="Равномерное-распределение-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Равномерное распределение</a></span></li><li><span><a href="#Случайные-перестановки-и-случайный-выбор" data-toc-modified-id="Случайные-перестановки-и-случайный-выбор-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Случайные перестановки и случайный выбор</a></span></li><li><span><a href="#Нормальное-распределение" data-toc-modified-id="Нормальное-распределение-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Нормальное распределение</a></span></li><li><span><a href="#Другие-распределения" data-toc-modified-id="Другие-распределения-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Другие распределения</a></span></li></ul></li></ul></div>

## Генерация случайных величин

Python (и все другое програмное обеспечение) генерирует случайные числа с помощью формул, так что они не на самом деле случайные, а, как говорят, псевдослучайные. Этот способ удобен для большинства приложений. Генерировать случайные числа мы будем с помощью numpy.

In [1]:
import numpy as np

### Seed

Для того, чтобы каждый раз при использовании генератора псевдослучайных чисел получать идентичные последовательности, используется функция set.seed (от set - задать, установить, и seed - начальное число). Как следует из названия, эта функция фиксирует число, служащее начальной точкой для запуска алгоритма генерации псевдослучайных чисел. В качестве аргумента функции указывают любое целое число (не важно, какое именно). 

* **np.random.seed(<число>)** —
настраивает генератор случайных чисел на новую последовательность. Если данная функция в программе не вызывается, по умолчанию используется системное время. 

In [2]:
np.random.seed(1) # Зафиксируем seed
print(np.random.rand()) # первое случайное число
print(np.random.rand()) # второе случайное число; оно будет отличаться от предыдущего

0.417022004702574
0.7203244934421581


In [3]:
# Но если мы обновим seed, то наша случайная последовательность будет генерироваться <<сначала>>
np.random.seed(1) 
print(np.random.rand())
print(np.random.rand())

0.417022004702574
0.7203244934421581


### Равномерное распределение

* **np.random.rand($\,\mathbf{d_0, d_1, \ldots, d_n}$)**  — генерирует массив размера $d_0\times d_1 \times \ldots \times d_n$ из равномерно распределенных на [0,1] случайных величин.

In [4]:
np.random.rand() # просто одно число

0.00011437481734488664

In [ ]:
np.random.rand(10) # одномерный массив из 10 чисел

array([0.30233257, 0.14675589, 0.09233859, 0.18626021, 0.34556073,
       0.39676747, 0.53881673, 0.41919451, 0.6852195 , 0.20445225])

In [5]:
np.random.rand(5,2) # двумерный массив размера [5,2]

array([[0.30233257, 0.14675589],
       [0.09233859, 0.18626021],
       [0.34556073, 0.39676747],
       [0.53881673, 0.41919451],
       [0.6852195 , 0.20445225]])

Для генерации из равномерного распределения на произвольном интервале можно использовать функцию:   
* **np.random.uniform([low, high, size])** — герирует массив размера [size] из равномерного распределения на $[low,high]$.

П.С. Альтернативно можно сгенерировать равномерно распределенные на $[0,1]$ случайные величины и применить к ним линейное преобразование

In [ ]:
np.random.normal

In [ ]:
np.random.uniform(5,10, size=[5,2])

array([[8.46161308, 9.38194576],
       [9.47303332, 5.42522106],
       [5.19527392, 5.8491521 ],
       [9.39071252, 5.49173417],
       [7.10553813, 9.78944765]])

Все следующие фукнции герерируют одномерный массив размера [size] из равномерно распределенных на [0,1] случайных величин. Но лучше пользоваться функциями **np.random.rand** или **np.random.uniform**, они чаще используются исследователями и программистами.

* **np.random.random_sample([size])**  
* **np.random.random([size])**  
* **np.random.ranf([size])**  
* **np.random.sample([size])**    

In [6]:
np.random.ranf(10)

array([0.87811744, 0.02738759, 0.67046751, 0.4173048 , 0.55868983,
       0.14038694, 0.19810149, 0.80074457, 0.96826158, 0.31342418])

Следующие функции генерируют случайные числа из равномерного распределения на целых числах:  
* **np.random.randint(low[, high, size, dtype])** — здесь вернхнее значение не включается в диапазон.  
* **np.random.random_integers(low[, high, size])** — здесь вернхнее значение включается в диапазон (но эта функция устарела, лучше использовать предыдущую).  

In [ ]:
np.random.randint(-1, 10, size = [2,10])

array([[ 6,  6,  9,  8,  7,  5,  8,  2,  6,  6],
       [ 3,  4,  8,  2,  5,  7, -1,  1,  9,  6]])

In [ ]:
np.random.random_integers(-1, 10, size= [2,10])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(-1, 10 + 1) instead
  """Entry point for launching an IPython kernel.


array([[ 6,  8,  6,  2,  9, -1,  7,  6,  6,  0],
       [ 0,  2, -1,  7,  5,  3,  4,  5,  1, 10]])

### Случайные перестановки и случайный выбор

Везде далее в качестве **x** можно использовать различные объекты: строку, список, кортеж...

* **np.random.shuffle(x)** — случайная перестановка последовательности **x** (меняет сам **x**, ничего не возвращает).  
* **np.random.permutation(x)** — случайная перестановка последовательности **x** (не меняет **x**, возвращает перестановку).


In [7]:
# для np.random.permutation следующий код имеет смысл
a = np.arange(5)
b = np.random.permutation(a)
print(a)
print(b)

[0 1 2 3 4]
[3 2 0 4 1]


In [8]:
# для np.random.shuffle — нет, так как мы поменяем a, и ничего не присвоим b
a = np.arange(5)
b = np.random.shuffle(a) 
print(a)
print(b)

[2 4 3 0 1]
None


* **random.choince(x)** — возвращает случайный элемент из последовательности **x**.

In [9]:
np.random.choice([1,2,3,7,0,88], )

7

### Нормальное распределение

* **np.random.randn($\,\mathbf{d_0, d_1, \ldots, d_n}$)**  — генерирует массив размера $d_0\times d_1 \times \ldots \times d_n$ из стандартного нормального распределения $\mathcal{N}(0,1)$. 

In [10]:
np.random.randn() # генерируем одно число

-0.17242820755043575

In [11]:
x = np.random.randn(1000)

In [12]:
x.mean(), x.var()

(0.03916848830707233, 0.9603155052082382)

In [ ]:
np.random.randn(2,3) # генерируем массив нужного размера

array([[ 0.52647831,  0.983809  , -1.92220001],
       [-0.89482523,  0.33006282,  1.048591  ]])

Следующая функция делает то же самое, но у нее немного другой синтаксис. Лучше пользоваться **np.random.randn**.   
* **np.random.standard_normal([size])** — генерирует массив размера [size] из стандартного нормального распределения $\mathcal{N}(0,1)$.



In [ ]:
np.random.standard_normal([2,5])

array([[ 1.34989935,  1.24567511, -0.69119147,  1.28107338, -0.72706431],
       [-0.79916869, -0.00354562,  0.51259464, -0.16786086,  1.34633628]])

Для нормального распредления с произвольными параметрами можно использовать следующую функцию:   
* **np.random.normal([loc, scale, size])** — генерируют массив размера [size] из нормального распределения $\mathcal{N}\bigl(loc,(scale)^2\bigr)$.

In [ ]:
np.random.normal(5,2, size = [5,2])

array([[3.76901604, 3.51392661],
       [7.03187226, 3.88968917],
       [5.87251872, 4.70662057],
       [5.04698565, 4.48339563],
       [8.67831238, 4.61202082]])

Чтобы сгенерировать многомерное нормальное распределение, можно воспользоваться следующей функцией:
* **np.random.multivariate_normal(mean, cov, [size])** — генерируют массив размера [size] из многомерного нормального распределения $\mathcal{N}(mean,cov)$.

In [15]:
d = 5 
mean = np.ones(d)
cov = 5*np.eye(d)

X = np.random.multivariate_normal(mean, cov, size = 100)

In [19]:
X.mean(axis=0)

array([1.30181969, 1.20713245, 1.19821665, 0.80067716, 1.43167876])

### Другие распределения

В качестве примера приведем еще фукции для распределений, которые мы упоминали в курсе по теории вероятностей:
* **np.random.binomial(n, p[, size])** — биномиальное распределение  
* **np.random.exponential([scale, size])** — экспоненциальное распределение  
* **np.random.poisson([lam, size])** — распределение Пуассона  
* **np.random.standard_cauchy([size])** — распределение Коши  

Полный список распределений можно посмотреть на: https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html

In [20]:
import scipy.stats as st

In [22]:
st.norm().rvs()

-1.814727087567263

In [24]:
st.norm().cdf(0)

0.5